# Generated by Django 6.1.1 on 2026-09-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150)),
                (
                    "group",
                    models.CharField(
                        choices=[("picker", "Отбор"), ("receiver", "Приемка"), ("shipper", "Отгрузка")], max_length=50
                    ),
                ),
                ("barcode", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "verbose_name": "Сотрудник",
                "verbose_name_plural": "Сотрудники",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Zone",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "zone_type",
                    models.CharField(
                        choices=[
                            ("receiving", "Приемка"),
                            ("storage", "Хранение"),
                            ("picking", "Отбор"),
                            ("shipping", "Отгрузка"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Зона",
                "verbose_name_plural": "Зоны",
                "ordering": ["zone_type"],
            },
        ),
    ]
