# Generated by Django 6.1.1 on 2026-09-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zone",
            name="zone_type",
            field=models.CharField(
                choices=[
                    ("receiving", "Приемка"),
                    ("storage", "Хранение"),
                    ("picking", "Отбор"),
                    ("shipping", "Отгрузка"),
                    ("gete", "Ворота отгрузки"),
                ],
                max_length=20,
            ),
        ),
    ]
