# Generated by Django 6.1.1 on 2026-09-08 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("goods", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rack",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("number", models.CharField(max_length=20, unique=True)),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="racks", to="core.zone"
                    ),
                ),
            ],
            options={
                "verbose_name": "Стеллаж",
                "verbose_name_plural": "Стеллажи",
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="Cell",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("number", models.CharField(max_length=20)),
                ("volume", models.DecimalField(decimal_places=2, help_text="Объем в м3", max_digits=10)),
                ("is_blocked_in", models.BooleanField(default=False)),
                ("is_blocked_out", models.BooleanField(default=False)),
                ("barcode", models.CharField(max_length=50, unique=True)),
                (
                    "rack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="cells", to="warehouse.rack"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ячейка",
                "verbose_name_plural": "Ячейки",
                "ordering": ["number"],
                "unique_together": {("rack", "number")},
            },
        ),
        migrations.CreateModel(
            name="StorageUnit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("type", models.CharField(choices=[("box", "Короб"), ("pallet", "Паллета")], max_length=10)),
                ("barcode", models.CharField(max_length=50, unique=True)),
                ("quantity", models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                (
                    "current_cell",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="storage_units",
                        to="warehouse.cell",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="warehouse.storageunit",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="goods.product"
                    ),
                ),
            ],
            options={
                "verbose_name": "Объект",
                "verbose_name_plural": "Объекты",
                "ordering": ["barcode"],
            },
        ),
    ]
