# Generated by Django 6.1.1 on 2026-09-13 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
        ("warehouse", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="storageunit",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                help_text="Кладовщик, которому выдана эта тара",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_totes",
                to="core.employee",
            ),
        ),
        migrations.AddField(
            model_name="storageunit",
            name="is_picking_tote",
            field=models.BooleanField(default=False, help_text="Является ли этот объект наборной тарой"),
        ),
    ]
