# Generated by Django 6.1.1 on 2026-09-13 11:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0002_storageunit_assigned_to_storageunit_is_picking_tote"),
    ]

    operations = [
        migrations.AddField(
            model_name="storageunit",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
