# Generated by Django 6.1.1 on 2026-09-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0003_storageunit_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storageunit",
            name="type",
            field=models.CharField(
                choices=[("box", "Короб"), ("pallet", "Паллета"), ("tote", "Наборная тара")], max_length=10
            ),
        ),
    ]
