# Generated by Django 6.1.1 on 2026-09-27 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0004_alter_storageunit_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="storageunit",
            name="is_closed",
            field=models.BooleanField(
                default=False,
                help_text="Для паллет: закрыта ли паллета (готова к размещению).",
                verbose_name="Закрыта",
            ),
        ),
        migrations.AddField(
            model_name="storageunit",
            name="is_opened_for_receiving",
            field=models.BooleanField(
                default=False, help_text="Для паллет: принимает ли сейчас короба.", verbose_name="Открыта для приёмки"
            ),
        ),
        migrations.AddField(
            model_name="storageunit",
            name="total_volume",
            field=models.DecimalField(
                decimal_places=4, default=0, help_text="Суммарный объём содержимого (для паллет)", max_digits=12
            ),
        ),
    ]
