# Generated by Django 6.1.1 on 2026-09-08 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PickingRoute",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                (
                    "strategy",
                    models.CharField(
                        choices=[
                            ("s_shape", "S-образный"),
                            ("zigzag", "Зигзаг"),
                            ("by_aisle", "По проходам"),
                            ("closest", "Ближайший"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="routes", to="core.zone"
                    ),
                ),
            ],
            options={
                "verbose_name": "Маршрут",
                "verbose_name_plural": "Маршруты обхода",
                "ordering": ["strategy"],
            },
        ),
    ]
