# Generated by Django 6.1.1 on 2026-09-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("weight", models.DecimalField(decimal_places=3, help_text="Вес", max_digits=10)),
                ("volume", models.DecimalField(decimal_places=3, help_text="Объем", max_digits=10)),
                ("width", models.DecimalField(decimal_places=2, help_text="Ширина", max_digits=10)),
                ("height", models.DecimalField(decimal_places=2, help_text="Высота", max_digits=10)),
                ("length", models.DecimalField(decimal_places=2, help_text="Длина", max_digits=10)),
                ("barcode", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
                "ordering": ["barcode"],
            },
        ),
    ]
