# Generated by Django 6.1.1 on 2026-09-08 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("orders", "0001_initial"),
        ("warehouse", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("putaway", "Размещение"),
                            ("pick", "Отбор"),
                            ("move", "Перемещение"),
                            ("replenishment", "Отгрузка"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=15)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "В очереди"),
                            ("in_progress", "В работе"),
                            ("done", "Выполнено"),
                            ("canceled", "Отменено"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="core.employee"
                    ),
                ),
                (
                    "order_line",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="orders.orderline"
                    ),
                ),
                (
                    "source_cell",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tasks_from",
                        to="warehouse.cell",
                    ),
                ),
                (
                    "storage_unit",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="warehouse.storageunit"),
                ),
                (
                    "target_cell",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tasks_to",
                        to="warehouse.cell",
                    ),
                ),
                (
                    "wave",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="orders.wave",
                    ),
                ),
            ],
            options={
                "verbose_name": "Операция",
                "verbose_name_plural": "Операции",
                "ordering": ["task_type"],
            },
        ),
        migrations.CreateModel(
            name="OperationLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("operation_type", models.CharField(max_length=20)),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=15)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("executor", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.employee")),
                (
                    "source_cell",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ops_from",
                        to="warehouse.cell",
                    ),
                ),
                (
                    "storage_unit",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="warehouse.storageunit"),
                ),
                (
                    "target_cell",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ops_to",
                        to="warehouse.cell",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="operations.task"),
                ),
            ],
            options={
                "verbose_name": "Отчеты",
                "verbose_name_plural": "Отчеты",
                "ordering": ["operation_type"],
            },
        ),
    ]
