# Generated by Django 6.1.1 on 2026-09-13 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0001_initial"),
        ("warehouse", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="storage_unit",
        ),
        migrations.AlterField(
            model_name="task",
            name="quantity",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Новое"),
                    ("in_progress", "Выполняется"),
                    ("done", "Выполнено"),
                    ("canceled", "Отменено"),
                ],
                default="new",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("putaway", "Размещение"),
                    ("pick", "Отбор"),
                    ("move", "Перемещение"),
                    ("replenishment", "Пополнение"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="TaskLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=15)),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "storage_unit",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="warehouse.storageunit"),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="lines", to="operations.task"
                    ),
                ),
            ],
            options={
                "verbose_name": "Строка заданий",
                "verbose_name_plural": "Строки заданий",
                "ordering": ["storage_unit"],
            },
        ),
    ]
