# Generated by Django 6.1.1 on 2026-09-13 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0002_remove_task_storage_unit_alter_task_quantity_and_more"),
        ("warehouse", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="picking_tote",
            field=models.ForeignKey(
                blank=True,
                help_text="Наборная тара, в которую собирается товар",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="picking_tasks",
                to="warehouse.storageunit",
            ),
        ),
        migrations.AlterField(
            model_name="taskline",
            name="storage_unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="task_lines", to="warehouse.storageunit"
            ),
        ),
    ]
