# Generated by Django 6.1.1 on 2026-09-27 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0003_task_picking_tote_alter_taskline_storage_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="operationlog",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Недостача, комментарий, пояснение — всё в текстовом виде.",
                null=True,
                verbose_name="Примечание",
            ),
        ),
        migrations.AlterField(
            model_name="operationlog",
            name="operation_type",
            field=models.CharField(
                choices=[
                    ("pick", "Отбор"),
                    ("move", "Перемещение"),
                    ("putaway", "Размещение"),
                    ("receive", "Приёмка"),
                    ("ship", "Отгрузка"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[("new", "Новое"), ("in_progress", "Выполняется"), ("done", "Выполнено")],
                default="new",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="task_type",
            field=models.CharField(
                choices=[("putaway", "Размещение"), ("pick", "Отбор"), ("move", "Перемещение")], max_length=20
            ),
        ),
    ]
