# Generated by Django 6.1.1 on 2026-09-08 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("goods", "0001_initial"),
        ("warehouse", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order_type", models.CharField(choices=[("in", "Входящая"), ("out", "Исходящая")], max_length=3)),
                ("counterparty", models.CharField(help_text="Контрагент", max_length=200)),
                ("order_number", models.CharField(max_length=50, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Ожидает"),
                            ("reserved", "Зарезервирована"),
                            ("picking", "В отборе"),
                            ("shipped", "Отгружена"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
                "ordering": ["status"],
            },
        ),
        migrations.CreateModel(
            name="OrderLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "requested_quantity",
                    models.DecimalField(decimal_places=3, help_text="Количество товара в заказе", max_digits=15),
                ),
                (
                    "reserved_quantity",
                    models.DecimalField(decimal_places=3, default=0, help_text="Зарезервированно", max_digits=15),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="lines", to="orders.order"
                    ),
                ),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="goods.product")),
            ],
            options={
                "verbose_name": "Строка заказа",
                "verbose_name_plural": "Строки заказа",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reserved_quantity", models.DecimalField(decimal_places=3, max_digits=15)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="reservations", to="orders.orderline"
                    ),
                ),
                (
                    "storage_unit",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="warehouse.storageunit"),
                ),
            ],
            options={
                "verbose_name": "Резерв",
                "verbose_name_plural": "Резервы",
                "ordering": ["order_line"],
            },
        ),
        migrations.CreateModel(
            name="Wave",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Наложена"), ("active", "В работе"), ("completed", "Завершена")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("params", models.JSONField(blank=True, default=dict)),
                ("orders", models.ManyToManyField(related_name="waves", to="orders.order")),
                ("zone", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.zone")),
            ],
            options={
                "verbose_name": "Волна",
                "verbose_name_plural": "Волны",
                "ordering": ["status"],
            },
        ),
    ]
