# Generated by Django 6.1.1 on 2026-09-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Ожидает"),
                    ("reserved", "Зарезервирована"),
                    ("picking", "В отборе"),
                    ("shipped", "Отгружена"),
                    ("picked", "Собран"),
                    ("shipping", "В отгрузке"),
                ],
                default="new",
                max_length=20,
            ),
        ),
    ]
