# Generated by Django 6.1.1 on 2026-09-27 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Ожидает"),
                    ("reserved", "Зарезервирована"),
                    ("picking", "В отборе"),
                    ("shipped", "Отгружена"),
                    ("picked", "Собран"),
                    ("shipping", "В отгрузке"),
                    ("receiving", "Приёмка"),
                    ("received", "Принята"),
                    ("putaway", "Размещение"),
                    ("stored", "Размещена"),
                ],
                default="new",
                max_length=20,
            ),
        ),
    ]
