# Generated by Django 6.1.1 on 2026-09-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderline",
            name="received_quantity",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                help_text="Сколько фактически принято (может отличаться от заказанного).",
                max_digits=15,
                verbose_name="Принято",
            ),
        ),
    ]
